-- ═══════════════════════════════════════════════════════════════════════
--  MUTFAK GROUP — VERİ MODELİ İYİLEŞTİRMELERİ  (isteğe bağlı, sonraki adım)
--  Bu dosya da OTOMATİK ÇALIŞTIRILMADI. 01-guvenlik-rls.sql tamamlanmadan
--  buna geçmeyin. Her bölüm arayüzde de değişiklik gerektirir; hangisini
--  istediğinizi söylerseniz uygulamayı ona göre güncelleyebilirim.
-- ═══════════════════════════════════════════════════════════════════════


-- ───────────────────────────────────────────────────────────────────────
-- A — Değişiklik zamanını veritabanı tutsun
-- ───────────────────────────────────────────────────────────────────────
-- Şu anda "son fiyat güncellemesi" bilgisini uygulama site_config içine
-- yazıyor. Asıl doğru yer satırın kendisi: kim ne zaman değişti, satır
-- bazında görünür olur.

alter table public.products
  add column if not exists updated_at timestamptz not null default now();

create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

drop trigger if exists products_touch_updated_at on public.products;
create trigger products_touch_updated_at
  before update on public.products
  for each row execute function public.touch_updated_at();

-- Bundan sonra en son fiyat güncellemesi tek satırla öğrenilir:
--   select max(updated_at) from public.products;


-- ───────────────────────────────────────────────────────────────────────
-- B — Fiyat metin değil sayı olsun
-- ───────────────────────────────────────────────────────────────────────
-- Fiyat şu an metin sütunu. "1.250,50" ile "1250.50" aynı üründe
-- karışabiliyor; toplama, sıralama ve raporlama yapılamıyor.
-- Uygulamanın yeni sürümü fiyatları zaten sade biçimde ("1250.5")
-- yazıyor, bu yüzden dönüşüm artık güvenli.
--
-- ÖNCE kontrol edin — bu sorgu sayıya çevrilemeyen satırları listeler.
-- Boş dönmeden dönüşümü YAPMAYIN:
--
--   select id, product_name, price from public.products
--    where coalesce(trim(price), '') <> ''
--      and price !~ '^-?[0-9]+(\.[0-9]+)?$';
--
-- Liste boşsa:
--
--   alter table public.products
--     alter column price type numeric(12,2)
--     using nullif(trim(price), '')::numeric;


-- ───────────────────────────────────────────────────────────────────────
-- C — Kategoriler kendi tablosuna taşınsın
-- ───────────────────────────────────────────────────────────────────────
-- Kategori bilgisi bugün her ürün satırında tekrarlanıyor. Sonuçları:
-- kategori adını değiştirmek bütün satırları yeniden yazıyor, boş kategori
-- var olamıyor (bu yüzden "(Yeni ürün)" sahte satırı gerekiyor) ve bir
-- kategorinin son ürününü silince kategori de kayboluyor.

create table if not exists public.categories (
  id          bigint generated by default as identity primary key,
  name_tr     text not null,
  name_en     text,
  group_key   text not null default 'other',
  sort_order  int  not null default 0,
  created_at  timestamptz not null default now()
);

-- Mevcut veriden kategorileri üret (bir kez çalıştırın)
insert into public.categories (id, name_tr, name_en, group_key, sort_order)
select distinct on (category_id)
       category_id, category_name, category_en,
       coalesce(category_group, 'other'), coalesce(category_order, 0)
  from public.products
 where category_id is not null
 order by category_id, id
on conflict (id) do nothing;

select setval(pg_get_serial_sequence('public.categories', 'id'),
              coalesce((select max(id) from public.categories), 1));

-- Yabancı anahtarı bağla (eski sütunları HEMEN silmeyin; arayüz
-- güncellenip bir süre sorunsuz çalıştıktan sonra silin)
alter table public.products
  add constraint products_category_fk
  foreign key (category_id) references public.categories(id) on delete cascade;

-- Arayüz yeni yapıya geçtikten ve doğrulandıktan SONRA:
--   alter table public.products
--     drop column category_name, drop column category_en,
--     drop column category_group, drop column category_order;
--   delete from public.products where product_name = '(Yeni ürün)';


-- ───────────────────────────────────────────────────────────────────────
-- D — Kullanılmayan sütun
-- ───────────────────────────────────────────────────────────────────────
-- spec3 hiçbir yerde okunmuyor ve yazılmıyor.
--   alter table public.products drop column spec3;
